#!/usr/bin/env python3


import os
import random
import collections as cl 
pairfile = "restpairs.txt"
fastafolder= "lifted/"
svfolder = "bench_pairwise/"

groupfiles = dict()
fastafiles = [x for x in os.listdir(fastafolder) ] 

for fastafile in fastafiles:

        if fastafile.endswith(".fa"):

                groupname = "_".join(fastafile.split("_")[:2])
                groupfiles[groupname] = fastafolder + fastafile

allpairs = set([])
with open (pairfile, mode ='r') as f:

        for line in f:
                pair = line.strip().split(",")
                allpairs.add((pair[0],pair[1]))

generegions = cl.defaultdict(str)

with open("./allliftedtitles.txt", mode = 'r') as f:
    for line in f:
        
        line = line.strip().split()

        if int(line[2]) - int(line[1]) > 100:
            generegions[line[0][1:]] = "{}-{}".format(line[1],line[2])




numrunjobs = 100
allpairs = list(allpairs)

rule all:
        input:
                chunks = ["results/{}_results".format(index) for index in range(numrunjobs)],


rule getpair:
    params:
        svfolder = svfolder,
    resources:
        mem_mb=20000,
        slurm_extra="--mem=20G -c 1 "
    threads: 1
    output:
        chunk = "results/{index}_results",
    run:
        index = int(output.chunk.split("/")[-1].split("_")[0])
        
        for i, pair in enumerate(allpairs):
            
            if i % numrunjobs != index:
                continue
            
            
            groupname= "_".join(pair[0].split("_")[:2])
            
            pair1 = pair[0]
            pair2 = pair[1]
            
            if groupname not in groupfiles or pair1 not in generegions or pair2 not in generegions:
                continue

            if pair1.endswith("NA") or pair2.endswith("NA"):
                continue
            
            if pair1 == pair2:
                continue
            
            align = "{}{}_pairwise_{}_output.txt".format(svfolder,pair[0],pair[1])
            alignextract = align+"_extract.fa"
            locioutput = alignextract + "_locityper"
            
            file1 = "{}{}.fa".format(svfolder,pair1)
            file2 = "{}{}.fa".format(svfolder,pair2)
            
            fastafile = groupfiles[groupname]
                        
            os.system("samtools faidx {} {} > {} ".format(fastafile,pair1,file1))
            os.system("samtools faidx {} {} > {} ".format(fastafile,pair2, file2))
            os.system('stretcher {} {} -snucleotide2  -gapopen 100  -gapextend 1  {}'.format(file1, file2,align))
            
            
            generegion1 = generegions[pair1]
            generegion2 = generegions[pair2]
            generegion = generegion1+","+generegion2
            
            os.system('python ../../../scripts/extractalign.py -i {} -r {} -o {}'.format(align, generegion,alignextract))
            os.system("./locityper align -i {} -A -o {}".format(alignextract, locioutput) )
            
            os.system('cat {} >> {} '.format(locioutput, output.chunk) )
            
        
            os.system('rm {} || true'.format(file1))
            os.system('rm {} || true'.format(file2))
            
            os.system('rm {} || true'.format(align))
            os.system('rm {} || true'.format(alignextract))
            os.system('rm {} || true'.format(locioutput))
                        
            
        shell (" touch {output.chunk} || true " )
